INSERT INTO campeones (NOMBRE_CAMPEON,REGION_DEL_CAMPEON) VALUES
('AATROX', 'RUNATERRA'),
('AHRI', 'JONIA'),
('AKALI', 'JONIA'),
('AKSHAN', 'SHURIMA'),
('ALISTAR', 'RUNATERRA'),
('AMUMU', 'SHURIMA'),
('ANIVIA', 'EL FRELJORD'),
('ANNIE', 'RUNATERRA'),
('APHELIOS', 'TARGON'),
('ASHE', 'EL FRELJORD'),
('AURELION SOL', 'RUNATERRA'),
('AZIR', 'SHURIMA'),
('BARDO', 'RUNATERRA'),
('BEL\'VETH', 'EL VACIO'),
('BLITZCRANK', 'ZAUN'),
('BRAND', 'RUNATERRA'),
('BRAUM', 'EL FRELJORD'),
('CAITLYN', 'PILTOVER'),
('CAMILLE', 'PILTOVER'),
('CASSIOPEIA', 'NOXUS'),
('CHO\'GATH', 'EL VACIO'),
('CORKI', 'CIUDAD DE BANDLE'),
('DARIUS', 'NOXUS'),
('DIANA', 'TARGON'),
('DR.MUNDO', 'ZAUN'),
('DRAVEN', 'NOXUS'),
('EKKO', 'ZAUN'),
('ELISE', 'ISLAS DE LA SOMBRA'),
('EVELYNN', 'RUNATERRA'),
('EZREAL', 'PILTOVER'),
('FIDDLESTICKS', 'RUNATERRA'),
('FIORA', 'DEMACIA'),
('FIZZ', 'RUNATERRA'),
('GALIO', 'DEMACIA'),
('GANGPLANK', 'AGUASTURBIAS'),
('GAREN', 'DEMACIA'),
('GNAR', 'EL FRELJORD'),
('GRAGAS', 'EL FRELJORD'),
('GRAVES', 'AGUASTURBIAS'),
('GWEN', 'ISLAS DE LA SOMBRA'),
('HECARIM', 'ISLAS DE LA SOMBRA'),
('HEIMERDINGER', 'PILTOVER'),
('ILLAOI', 'AGUASTURBIAS'),
('IRELIA', 'JONIA'),
('IVERN', 'JONIA'),
('JANNA', 'ZAUN'),
('JARVAN IV', 'DEMACIA'),
('JAX', 'RUNATERRA'),
('JAYCE', 'PILTOVER'),
('JHIN', 'JONIA'),
('JINX', 'ZAUN'),
('KAI\'SA', 'EL VACIO'),
('KALISTA', 'ISLAS DE LAS SOMBRAS'),
('KARMA', 'JONIA'),
('KARTHUS', 'ISLAS DE LAS SOMBRAS'),
('KASSADIN', 'EL VACIO'),
('KATARINA', 'NOXUS'),
('KAYLE', 'DEMACIA'),
('KAYN', 'JONIA'),
('KENNEN', 'JONIA'),
('KHA\'SIX', 'EL VACIO'),
('KINDRED', 'RUNATERRA'),
('KLED', 'NOXUS'),
('KOG\'MAW', 'EL VACIO'),
('K\'SANTE', 'SHURIMA'),
('LEBLANC', 'NOXUS'),
('LEE SIN', 'JONIA'),
('LEONA', 'TARGON'),
('LILLIA', 'JONIA'),
('LISSANDRA', 'EL FRELJORD'),
('LUCIAN', 'RUNATERRA'),
('LULU', 'CIUDAD DE BANDLE'),
('LUX', 'DEMACIA'),
('MAESTRO YI', 'JONIA'),
('MALPHITE', '???'),
('MALZAHAR', 'EL VACIO'),
('MAOKAI', 'ISLAS DE LA SOMBRA'),
('MISS FORTUNE', 'AGUASTURBIAS'),
('MORDEKAISER', 'NOXUS'),
('MORGANA', 'DEMACIA'),
('NAMI', 'RUNATERRA'),
('NASUS', 'SHURIMA'),
('NAUTILUS', 'AGUASTURBIAS'),
('NEEKO', '???'),
('NIDALEE', '???'),
('NILAH', 'AGUASTURBIAS'),
('NOCTURNE', 'RUNATERRA'),
('NUNU Y WILLUMP', 'EL FRELJORD'),
('OLAF', 'EL FRELJORD'),
('ORIANNA', 'PILTOVER'),
('ORNN', 'EL FRELJORD'),
('PANTHEON', 'TARGON'),
('POPPY', 'DEMACIA'),
('PYKE', 'AGUASTURBIAS'),
('QIYANA', '???'),
('QUINN', 'DEMACIA'),
('RAKAN', 'JONIA'),
('RAMMUS', 'SHURIMA'),
('REK\'SAI', 'EL VACIO'),
('RELL', 'NOXUS'),
('RENATA GLASC', 'ZAUN'),
('RENEKTON', 'SHURIMA'),
('RENGAR', '???'),
('RIVEN', 'NOXUS'),
('RUMBLE', 'CIUDAD DE BANDLE'),
('RYZE', 'RUNATERRA'),
('SAMIRA', 'NOXUS'),
('SEJUANI', 'EL FRELJORD'),
('SENNA', 'RUNATERRA'),
('SERAPHINE', 'PILTOVER'),
('SETT', 'JONIA'),
('SHACO', 'RUNATERRA'),
('SHEN', 'JONIA'),
('SHYVANA', 'DEMACIA'),
('SINGED', 'ZAUN'),
('SION', 'NOXUS'),
('SIVIR', 'SHURIMA'),
('SKARNER', 'SHURIMA'),
('SONA', 'DEMACIA'),
('SORAKA', 'TARGON'),
('SWAIN', 'NOXUS'),
('SYLAS', 'DEMACIA'),
('SYNDRA', 'JONIA'),
('TAHM KENCH', 'RUNATERRA'),
('TALIYAH', 'SHURIMA'),
('TALON', 'NOXUS'),
('TARIC', 'TARGON'),
('TEEMO', 'CIUDAD DE BANDLE'),
('THRESH', 'ISLAS DE LA SOMBRA'),
('TRISTANA', 'CIUDAD DE BANDLE'),
('TRUNDLE', 'EL FRELJORD'),
('TRYNDAMERE', 'EL FRELJORD'),
('TWISTED FATE', 'AGUASTURBIAS'),
('TWITCH', 'ZAUN'),
('UDYR', 'EL FRELJORD'),
('URGOT', 'ZAUN'),
('VARUS', 'JONIA'),
('VAYNE', 'DEMACIA'),
('VEIGAR', 'CIUDAD DE BANDLE'),
('VEL\'KOZ', 'EL VACIO'),
('VEX', 'ISLAS DE LA SOMBRA'),
('VI', 'PILTOVER'),
('VIEGO', 'ISLAS DE LA SOMBRA'),
('VIKTOR', 'ZAUN'),
('VLADIMIR', 'NOXUS'),
('VOLIBEAR', 'EL FRELJORD'),
('WARWICK', 'ZAUN'),
('WUKONG', 'JONIA'),
('XAYAH', 'JONIA'),
('XERATH', 'SHURIMA'),
('XIN ZHAO', 'DEMACIA'),
('YASUO', 'JONIA'),
('YONE', 'JONIA'),
('YORICK', 'ISLAS DE LA SOMBRA'),
('YUUMI', 'CIUDAD DE BANDLE'),
('ZAC', 'ZAUN'),
('ZED', 'JONIA'),
('ZERI', 'ZAUN'),
('ZIGGS', 'ZAUN'),
('ZILEAN', 'RUNATERRA'),
('ZOE', 'TARGON'),
('ZYRA', '???');

INSERT INTO ligas (REGION,DENOMINACION) VALUES
('CHINA', 'LPL'),
('COREA', 'LCK'),
('EUROPA', 'LEC'),
('AMERICA DEL NORTE', 'LCS'),
('TAIWAN,HONG KONG,MACAO Y SUDESTE ASIATICO', 'PCS'),
('VIETNAM', 'VCS'),
('BRASIL', 'CBLOL'),
('JAPON', 'LJL');

INSERT INTO PAISES (NOMBRE, DOMINIO) VALUES
  ('Afganistán','AF'),
  ('Albania','AL'),
  ('Alemania','DE'),
  ('Andorra','AD'),
  ('Angola','AO'),
  ('Anguila','AI'),
  ('Antártida','AQ'),
  ('Antigua y Barbuda','AG'),
  ('Arabia Saudita','SA'),
  ('Argelia','DZ'),
  ('Argentina','AR'),
  ('Armenia','AM'),
  ('Aruba','AW'),
  ('Australia','AU'),
  ('Austria','AT'),
  ('Azerbaiyán','AZ'),
  ('Bélgica','BE'),
  ('Bahamas','BS'),
  ('Bahrein','BH'),
  ('Bangladesh','BD'),
  ('Barbados','BB'),
  ('Belice','BZ'),
  ('Benín','BJ'),
  ('Bhután','BT'),
  ('Bielorrusia','BY'),
  ('Birmania','MM'),
  ('Bolivia','BO'),
  ('Bosnia y Herzegovina','BA'),
  ('Botsuana','BW'),
  ('Brasil','BR'),
  ('Brunéi','BN'),
  ('Bulgaria','BG'),
  ('Burkina Faso','BF'),
  ('Burundi','BI'),
  ('Cabo Verde','CV'),
  ('Camboya','KH'),
  ('Camerún','CM'),
  ('Canadá','CA'),
  ('Chad','TD'),
  ('Chile','CL'),
  ('China','CN'),
  ('Chipre','CY'),
  ('Ciudad del Vaticano','VA'),
  ('Colombia','CO'),
  ('Comoras','KM'),
  ('República del Congo','CG'),
  ('República Democrática del Congo','CD'),
  ('Corea del Norte','KP'),
  ('Corea del Sur','KR'),
  ('Costa de Marfil','CI'),
  ('Costa Rica','CR'),
  ('Croacia','HR'),
  ('Cuba','CU'),
  ('Curazao','CW'),
  ('Dinamarca','DK'),
  ('Dominica','DM'),
  ('Ecuador','EC'),
  ('Egipto','EG'),
  ('El Salvador','SV'),
  ('Emiratos Árabes Unidos','AE'),
  ('Eritrea','ER'),
  ('Eslovaquia','SK'),
  ('Eslovenia','SI'),
  ('España','ES'),
  ('Estados Unidos de América','US'),
  ('Estonia','EE'),
  ('Etiopía','ET'),
  ('Filipinas','PH'),
  ('Finlandia','FI'),
  ('Fiyi','FJ'),
  ('Francia','FR'),
  ('Gabón','GA'),
  ('Gambia','GM'),
  ('Georgia','GE'),
  ('Ghana','GH'),
  ('Gibraltar','GI'),
  ('Granada','GD'),
  ('Grecia','GR'),
  ('Groenlandia','GL'),
  ('Guadalupe','GP'),
  ('Guam','GU'),
  ('Guatemala','GT'),
  ('Guayana Francesa','GF'),
  ('Guernsey','GG'),
  ('Guinea','GN'),
  ('Guinea Ecuatorial','GQ'),
  ('Guinea-Bissau','GW'),
  ('Guyana','GY'),
  ('Haití','HT'),
  ('Honduras','HN'),
  ('Hong kong','HK'),
  ('Hungría','HU'),
  ('India','IN'),
  ('Indonesia','ID'),
  ('Irán','IR'),
  ('Irak','IQ'),
  ('Irlanda','IE'),
  ('Isla Bouvet','BV'),
  ('Isla de Man','IM'),
  ('Isla de Navidad','CX'),
  ('Isla Norfolk','NF'),
  ('Islandia','IS'),
  ('Islas Bermudas','BM'),
  ('Islas Caimán','KY'),
  ('Islas Cocos (Keeling)','CC'),
  ('Islas Cook','CK'),
  ('Islas de Åland','AX'),
  ('Islas Feroe','FO'),
  ('Islas Georgias del Sur y Sandwich del Sur','GS'),
  ('Islas Heard y McDonald','HM'),
  ('Islas Maldivas','MV'),
  ('Islas Malvinas','FK'),
  ('Islas Marianas del Norte','MP'),
  ('Islas Marshall','MH'),
  ('Islas Pitcairn','PN'),
  ('Islas Salomón','SB'),
  ('Islas Turcas y Caicos','TC'),
  ('Islas Ultramarinas Menores de Estados Unidos','UM'),
  ('Islas Vírgenes Británicas','VG'),
  ('Islas Vírgenes de los Estados Unidos','VI'),
  ('Israel','IL'),
  ('Italia','IT'),
  ('Jamaica','JM'),
  ('Japón','JP'),
  ('Jersey','JE'),
  ('Jordania','JO'),
  ('Kazajistán','KZ'),
  ('Kenia','KE'),
  ('Kirguistán','KG'),
  ('Kiribati','KI'),
  ('Kuwait','KW'),
  ('Líbano','LB'),
  ('Laos','LA'),
  ('Lesoto','LS'),
  ('Letonia','LV'),
  ('Liberia','LR'),
  ('Libia','LY'),
  ('Liechtenstein','LI'),
  ('Lituania','LT'),
  ('Luxemburgo','LU'),
  ('México','MX'),
  ('Mónaco','MC'),
  ('Macao','MO'),
  ('Macedônia','MK'),
  ('Madagascar','MG'),
  ('Malasia','MY'),
  ('Malawi','MW'),
  ('Mali','ML'),
  ('Malta','MT'),
  ('Marruecos','MA'),
  ('Martinica','MQ'),
  ('Mauricio','MU'),
  ('Mauritania','MR'),
  ('Mayotte','YT'),
  ('Micronesia','FM'),
  ('Moldavia','MD'),
  ('Mongolia','MN'),
  ('Montenegro','ME'),
  ('Montserrat','MS'),
  ('Mozambique','MZ'),
  ('Namibia','NA'),
  ('Nauru','NR'),
  ('Nepal','NP'),
  ('Nicaragua','NI'),
  ('Niger','NE'),
  ('Nigeria','NG'),
  ('Niue','NU'),
  ('Noruega','NO'),
  ('Nueva Caledonia','NC'),
  ('Nueva Zelanda','NZ'),
  ('Omán','OM'),
  ('Países Bajos','NL'),
  ('Pakistán','PK'),
  ('Palau','PW'),
  ('Palestina','PS'),
  ('Panamá','PA'),
  ('Papúa Nueva Guinea','PG'),
  ('Paraguay','PY'),
  ('Perú','PE'),
  ('Polinesia Francesa','PF'),
  ('Polonia','PL'),
  ('Portugal','PT'),
  ('Puerto Rico','PR'),
  ('Qatar','QA'),
  ('Reino Unido','GB'),
  ('República Centroafricana','CF'),
  ('República Checa','CZ'),
  ('República Dominicana','DO'),
  ('República de Sudán del Sur','SS'),
  ('Reunión','RE'),
  ('Ruanda','RW'),
  ('Rumanía','RO'),
  ('Rusia','RU'),
  ('Sahara Occidental','EH'),
  ('Samoa','WS'),
  ('Samoa Americana','AS'),
  ('San Bartolomé','BL'),
  ('San Cristóbal y Nieves','KN'),
  ('San Marino','SM'),
  ('San Martín (Francia)','MF'),
  ('San Pedro y Miquelón','PM'),
  ('San Vicente y las Granadinas','VC'),
  ('Santa Elena','SH'),
  ('Santa Lucía','LC'),
  ('Santo Tomé y Príncipe','ST'),
  ('Senegal','SN'),
  ('Serbia','RS'),
  ('Seychelles','SC'),
  ('Sierra Leona','SL'),
  ('Singapur','SG'),
  ('Sint Maarten','SX'),
  ('Siria','SY'),
  ('Somalia','SO'),
  ('Sri lanka','LK'),
  ('Sudáfrica','ZA'),
  ('Sudán','SD'),
  ('Suecia','SE'),
  ('Suiza','CH'),
  ('Surinám','SR'),
  ('Svalbard y Jan Mayen','SJ'),
  ('Swazilandia','SZ'),
  ('Tayikistán','TJ'),
  ('Tailandia','TH'),
  ('Taiwán','TW'),
  ('Tanzania','TZ'),
  ('Territorio Británico del Océano Índico','IO'),
  ('Territorios Australes y Antárticas Franceses','TF'),
  ('Timor Oriental','TL'),
  ('Togo','TG'),
  ('Tokelau','TK'),
  ('Tonga','TO'),
  ('Trinidad y Tobago','TT'),
  ('Tunez','TN'),
  ('Turkmenistán','TM'),
  ('Turquía','TR'),
  ('Tuvalu','TV'),
  ('Ucrania','UA'),
  ('Uganda','UG'),
  ('Uruguay','UY'),
  ('Uzbekistán','UZ'),
  ('Vanuatu','VU'),
  ('Venezuela','VE'),
  ('Vietnam','VN'),
  ('Wallis y Futuna','WF'),
  ('Yemen','YE'),
  ('Yibuti','DJ'),
  ('Zambia','ZM'),
  ('Zimbabue','ZW');

INSERT INTO posiciones (CARRIL) VALUES
('CARRIL SUP'),
('JUNGLA'),
('CARRIL CEN'),
('CARRIL INF'),
('SOPORTE');


INSERT INTO servidores (NOMBRE_DEL_SERVIDOR) VALUES
('LAN'),
('LAS'),
('NA'),
('EUW'),
('JP'),
('OCE'),
('RU'),
('TR'),
('KR');

INSERT INTO jugadores (NOMBRE,FECHA_DE_NACIMIENTO,PAIS,ID_SERVIDOR,ID_POSICION,ID_CAMPEON,ID_LIGA) VALUES
("KANG SEUNG-LOK (THESHY)","1999-11-11",49,9,1,32,1),
("MARTIN NORDAHL HANSEN (WUNDER)","1998-11-09",55,4,1,1,3),
("LEE-SANG-HYEOK (FAKER)","1996-5-7",49,9,3,66,2),
("RASMUS BORREGAARD WINTHER (CAPS)","1999-11-17",55,4,3,122,3),
("BRANDON JOEL VILLEGAS (JOSEDEODO)","2000-05-22",11,3,2,67,4),
("GAO TIAN-LIANG (TIAN)","2000-07-24",41,9,2,67,1),
("PARK JIN-SEONG (TEDDY)","1998-03-15",49,9,4,30,2),
("KIM HYUK-KYU (DEFT)","1996-10-23",49,9,4,51,2),
("LEE JAE-WAN (WOLF)","1996-09-09",49,9,5,5,2),
("KERIA RYU MIN-SEOK (KERIA)","2002-10-14",49,9,5,129,2);
