CREATE DATABASE IF NOT EXISTS LeagueofLegends;

USE LeagueofLegends;

CREATE TABLE LIGAS 
(
    LIGAS_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    REGION VARCHAR (30) NOT NULL,
    DENOMINACION CHAR (10) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PAISES
(
    PAIS_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DOMINIO CHAR(2) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CAMPEONES 
(
    CAMPEONES_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CAMPEON VARCHAR (50) NOT NULL,
    REGION_DEL_CAMPEON VARCHAR (60) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SERVIDORES
(
    SERVIDORES_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DEL_SERVIDOR VARCHAR (60) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE POSICIONES
(
    POSICIONES_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CARRIL VARCHAR (10) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE JUGADORES 
(
	JUGADORES_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR (50) NOT NULL,
    FECHA_DE_NACIMIENTO DATE,
    PAIS INTEGER UNSIGNED,
    FOREIGN KEY (PAIS)
    	REFERENCES PAISES(PAIS_ID)
    	ON DELETE CASCADE 
    	ON UPDATE CASCADE,
    ID_SERVIDOR INTEGER UNSIGNED,
    FOREIGN KEY (ID_SERVIDOR)
    	REFERENCES SERVIDORES(SERVIDORES_ID)
    	ON DELETE RESTRICT 
    	ON UPDATE CASCADE,
    ID_POSICION INTEGER UNSIGNED,
    FOREIGN KEY (ID_POSICION)
    	REFERENCES POSICIONES(POSICIONES_ID)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE,
    ID_CAMPEON INTEGER UNSIGNED,
    FOREIGN KEY (ID_CAMPEON)
    	REFERENCES CAMPEONES(CAMPEONES_ID)
    	ON DELETE RESTRICT 
    	ON UPDATE CASCADE,
    ID_LIGA INTEGER UNSIGNED,
    FOREIGN KEY (ID_LIGA)
    	REFERENCES LIGAS(LIGAS_ID)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;